added sysconfig for rpm to control init script to be enabled or disabled

diff --git a/bin/init.d/diamond b/bin/init.d/diamond
--- a/bin/init.d/diamond
+++ b/bin/init.d/diamond
@@ -28,6 +28,18 @@ SCRIPTNAME=/etc/init.d/diamond
 LOCKDIR=/var/lock/subsys
 LOCKFILE=/var/lock/subsys/diamond
 
+# Exit if the package is not installed
+[ -x $DAEMON ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/sysconfig/$NAME ] && . /etc/sysconfig/$NAME
+
+# Checking for a config file in place
+if [  ! -e $CONF ]; then
+   echo "/etc/diamond/diamond.conf not found. Please see /etc/diamond/diamond.conf.example"
+   exit 2
+fi
+
 . /etc/rc.d/init.d/functions
 
 start() {
